/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InvitationRouteImport } from './routes/invitation'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedBienvenueRouteImport } from './routes/_authenticated/bienvenue'
import { Route as AuthenticatedMesSessionsRouteImport } from './routes/_authenticated/mes-sessions'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedPilotageRouteImport } from './routes/_authenticated/pilotage'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as AuthenticatedFormateursIndexRouteImport } from './routes/_authenticated/formateurs/index'
import { Route as AuthenticatedFormateursTrainerIdRouteImport } from './routes/_authenticated/formateurs/$trainerId'
import { Route as AuthenticatedParticipantsIndexRouteImport } from './routes/_authenticated/participants/index'
import { Route as AuthenticatedParticipantsParticipantIdRouteImport } from './routes/_authenticated/participants/$participantId'
import { Route as AuthenticatedProgrammesIndexRouteImport } from './routes/_authenticated/programmes/index'
import { Route as AuthenticatedProgrammesProgramIdRouteImport } from './routes/_authenticated/programmes/$programId'
import { Route as AuthenticatedSessionsSessionIdRouteImport } from './routes/_authenticated/sessions/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationRoute = InvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBienvenueRoute = AuthenticatedBienvenueRouteImport.update({
  id: '/bienvenue',
  path: '/bienvenue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesSessionsRoute =
  AuthenticatedMesSessionsRouteImport.update({
    id: '/mes-sessions',
    path: '/mes-sessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPilotageRoute = AuthenticatedPilotageRouteImport.update({
  id: '/pilotage',
  path: '/pilotage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormateursIndexRoute =
  AuthenticatedFormateursIndexRouteImport.update({
    id: '/formateurs/',
    path: '/formateurs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormateursTrainerIdRoute =
  AuthenticatedFormateursTrainerIdRouteImport.update({
    id: '/formateurs/$trainerId',
    path: '/formateurs/$trainerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParticipantsIndexRoute =
  AuthenticatedParticipantsIndexRouteImport.update({
    id: '/participants/',
    path: '/participants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParticipantsParticipantIdRoute =
  AuthenticatedParticipantsParticipantIdRouteImport.update({
    id: '/participants/$participantId',
    path: '/participants/$participantId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammesIndexRoute =
  AuthenticatedProgrammesIndexRouteImport.update({
    id: '/programmes/',
    path: '/programmes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammesProgramIdRoute =
  AuthenticatedProgrammesProgramIdRouteImport.update({
    id: '/programmes/$programId',
    path: '/programmes/$programId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsSessionIdRoute =
  AuthenticatedSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invitation': typeof InvitationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bienvenue': typeof AuthenticatedBienvenueRoute
  '/mes-sessions': typeof AuthenticatedMesSessionsRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/pilotage': typeof AuthenticatedPilotageRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/formateurs/$trainerId': typeof AuthenticatedFormateursTrainerIdRoute
  '/participants/$participantId': typeof AuthenticatedParticipantsParticipantIdRoute
  '/programmes/$programId': typeof AuthenticatedProgrammesProgramIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/formateurs/': typeof AuthenticatedFormateursIndexRoute
  '/participants/': typeof AuthenticatedParticipantsIndexRoute
  '/programmes/': typeof AuthenticatedProgrammesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invitation': typeof InvitationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bienvenue': typeof AuthenticatedBienvenueRoute
  '/mes-sessions': typeof AuthenticatedMesSessionsRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/pilotage': typeof AuthenticatedPilotageRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/formateurs/$trainerId': typeof AuthenticatedFormateursTrainerIdRoute
  '/participants/$participantId': typeof AuthenticatedParticipantsParticipantIdRoute
  '/programmes/$programId': typeof AuthenticatedProgrammesProgramIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/formateurs': typeof AuthenticatedFormateursIndexRoute
  '/participants': typeof AuthenticatedParticipantsIndexRoute
  '/programmes': typeof AuthenticatedProgrammesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/invitation': typeof InvitationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/bienvenue': typeof AuthenticatedBienvenueRoute
  '/_authenticated/mes-sessions': typeof AuthenticatedMesSessionsRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/pilotage': typeof AuthenticatedPilotageRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/_authenticated/formateurs/$trainerId': typeof AuthenticatedFormateursTrainerIdRoute
  '/_authenticated/participants/$participantId': typeof AuthenticatedParticipantsParticipantIdRoute
  '/_authenticated/programmes/$programId': typeof AuthenticatedProgrammesProgramIdRoute
  '/_authenticated/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/_authenticated/formateurs/': typeof AuthenticatedFormateursIndexRoute
  '/_authenticated/participants/': typeof AuthenticatedParticipantsIndexRoute
  '/_authenticated/programmes/': typeof AuthenticatedProgrammesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/invitation'
    | '/reset-password'
    | '/bienvenue'
    | '/mes-sessions'
    | '/parametres'
    | '/pilotage'
    | '/tableau-de-bord'
    | '/formateurs/$trainerId'
    | '/participants/$participantId'
    | '/programmes/$programId'
    | '/sessions/$sessionId'
    | '/formateurs/'
    | '/participants/'
    | '/programmes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/invitation'
    | '/reset-password'
    | '/bienvenue'
    | '/mes-sessions'
    | '/parametres'
    | '/pilotage'
    | '/tableau-de-bord'
    | '/formateurs/$trainerId'
    | '/participants/$participantId'
    | '/programmes/$programId'
    | '/sessions/$sessionId'
    | '/formateurs'
    | '/participants'
    | '/programmes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/invitation'
    | '/reset-password'
    | '/_authenticated/bienvenue'
    | '/_authenticated/mes-sessions'
    | '/_authenticated/parametres'
    | '/_authenticated/pilotage'
    | '/_authenticated/tableau-de-bord'
    | '/_authenticated/formateurs/$trainerId'
    | '/_authenticated/participants/$participantId'
    | '/_authenticated/programmes/$programId'
    | '/_authenticated/sessions/$sessionId'
    | '/_authenticated/formateurs/'
    | '/_authenticated/participants/'
    | '/_authenticated/programmes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InvitationRoute: typeof InvitationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation': {
      id: '/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof InvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bienvenue': {
      id: '/_authenticated/bienvenue'
      path: '/bienvenue'
      fullPath: '/bienvenue'
      preLoaderRoute: typeof AuthenticatedBienvenueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-sessions': {
      id: '/_authenticated/mes-sessions'
      path: '/mes-sessions'
      fullPath: '/mes-sessions'
      preLoaderRoute: typeof AuthenticatedMesSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pilotage': {
      id: '/_authenticated/pilotage'
      path: '/pilotage'
      fullPath: '/pilotage'
      preLoaderRoute: typeof AuthenticatedPilotageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formateurs/': {
      id: '/_authenticated/formateurs/'
      path: '/formateurs'
      fullPath: '/formateurs/'
      preLoaderRoute: typeof AuthenticatedFormateursIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formateurs/$trainerId': {
      id: '/_authenticated/formateurs/$trainerId'
      path: '/formateurs/$trainerId'
      fullPath: '/formateurs/$trainerId'
      preLoaderRoute: typeof AuthenticatedFormateursTrainerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/participants/': {
      id: '/_authenticated/participants/'
      path: '/participants'
      fullPath: '/participants/'
      preLoaderRoute: typeof AuthenticatedParticipantsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/participants/$participantId': {
      id: '/_authenticated/participants/$participantId'
      path: '/participants/$participantId'
      fullPath: '/participants/$participantId'
      preLoaderRoute: typeof AuthenticatedParticipantsParticipantIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programmes/': {
      id: '/_authenticated/programmes/'
      path: '/programmes'
      fullPath: '/programmes/'
      preLoaderRoute: typeof AuthenticatedProgrammesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programmes/$programId': {
      id: '/_authenticated/programmes/$programId'
      path: '/programmes/$programId'
      fullPath: '/programmes/$programId'
      preLoaderRoute: typeof AuthenticatedProgrammesProgramIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$sessionId': {
      id: '/_authenticated/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBienvenueRoute: typeof AuthenticatedBienvenueRoute
  AuthenticatedMesSessionsRoute: typeof AuthenticatedMesSessionsRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedPilotageRoute: typeof AuthenticatedPilotageRoute
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedFormateursTrainerIdRoute: typeof AuthenticatedFormateursTrainerIdRoute
  AuthenticatedParticipantsParticipantIdRoute: typeof AuthenticatedParticipantsParticipantIdRoute
  AuthenticatedProgrammesProgramIdRoute: typeof AuthenticatedProgrammesProgramIdRoute
  AuthenticatedSessionsSessionIdRoute: typeof AuthenticatedSessionsSessionIdRoute
  AuthenticatedFormateursIndexRoute: typeof AuthenticatedFormateursIndexRoute
  AuthenticatedParticipantsIndexRoute: typeof AuthenticatedParticipantsIndexRoute
  AuthenticatedProgrammesIndexRoute: typeof AuthenticatedProgrammesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBienvenueRoute: AuthenticatedBienvenueRoute,
  AuthenticatedMesSessionsRoute: AuthenticatedMesSessionsRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedPilotageRoute: AuthenticatedPilotageRoute,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedFormateursTrainerIdRoute: AuthenticatedFormateursTrainerIdRoute,
  AuthenticatedParticipantsParticipantIdRoute:
    AuthenticatedParticipantsParticipantIdRoute,
  AuthenticatedProgrammesProgramIdRoute: AuthenticatedProgrammesProgramIdRoute,
  AuthenticatedSessionsSessionIdRoute: AuthenticatedSessionsSessionIdRoute,
  AuthenticatedFormateursIndexRoute: AuthenticatedFormateursIndexRoute,
  AuthenticatedParticipantsIndexRoute: AuthenticatedParticipantsIndexRoute,
  AuthenticatedProgrammesIndexRoute: AuthenticatedProgrammesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InvitationRoute: InvitationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
